spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: audi
    password: audi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/customer
    payment-url: http://localhost:8222/api/v1/payment
    product-url: http://localhost:8222/api/v1/product